version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: foodstock_db
    environment:
      POSTGRES_DB: food_stock
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - foodstock_network

  backend_node1:
    build: 
      context: ./backend
    container_name: foodstock_back1
    environment:
      - PORT=3000
      - DB_HOST=postgres_db
      - DB_USER=admin
      - DB_PASSWORD=password123
      - DB_NAME=food_stock
      - DB_PORT=5432
    depends_on:
      - postgres_db
    networks:
      - foodstock_network

  backend_node2:
    build: 
      context: ./backend
    container_name: foodstock_back2
    environment:
      - PORT=3000
      - DB_HOST=postgres_db
      - DB_USER=admin
      - DB_PASSWORD=password123
      - DB_NAME=food_stock
      - DB_PORT=5432
    depends_on:
      - postgres_db
    networks:
      - foodstock_network

  backend_node3:
    build: 
      context: ./backend
    container_name: foodstock_back3
    environment:
      - PORT=3000
      - DB_HOST=postgres_db
      - DB_USER=admin
      - DB_PASSWORD=password123
      - DB_NAME=food_stock
      - DB_PORT=5432
    depends_on:
      - postgres_db
    networks:
      - foodstock_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: foodstock_front
    # Nota: Quitamos el 'depends_on' estricto hacia los nodos del backend aquí 
    # ya que el flujo de red se controlará a través de las peticiones del cliente o el balanceador.
    networks:
      - foodstock_network

  balancer_nginx:
    image: nginx:alpine
    container_name: balanceador_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend_node1
      - backend_node2
      - backend_node3
    networks:
      - foodstock_network

volumes:
  pgdata:

networks:
  foodstock_network:
    driver: bridge